### ISSUE TITLE
[Inky] Menu updates

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#247]
Todo:
- [x] add `<th>` tags to CSS so it is responsive in Android 4.4 - Resolves https://github.com/zurb/foundation-emails/issues/241
- [x] remove padding, padding-right if needed (styled like simple inline list) - Resolves https://github.com/zurb/foundation-emails/issues/233
- [x] get rid of simple class
- [x] Menu links not blue in Outlook - Resolves https://github.com/zurb/foundation-emails/issues/231
- [x] in Inky, add width attribute `width="600"`
- [x] In Inky, `<center>` tags wrapped around should add `align: center` - Resolves https://github.com/zurb/foundation-emails/issues/238
- [x] In Inky, `<center>` tags wrapped around menu should add .float-center to each .menu-item.

**Comment by rafibomb** [comment]
Todo: 
- remove padding, padding-right if needed
- get rid of simple class
- in Inky, add width attribute `width="600"`

**Comment by tdhartwick** [comment]
Fixed the CSS and HTML for menus. Here are the significant changes that will effect Inky @kball:
- Needs another `<table>` so that padding is respected.
- Classes are updated. We now include `.menu-item`.

These changes are reflected in the new `menu.html` in the testbed. Simple menus are now obsolete!

We still need to optimize the CSS, but it works as expected in all email clients!

**Comment by gakimball** [comment]
`<center>` and `<menu>` fixes implemented via zurb/inky@97fde356d79602e3c8ac9789d3d081df18e6b9eb

**Comment by gakimball** [comment]
All Inky updates are in 1.2.6. Passing assignment to @tdhartwick  for the last menu issue.

**Comment by rafibomb** [comment]
@gakimball Can you help with the last item?

**Comment by gakimball** [comment]
Updates to `<center>` and `<item>` via zurb/inky@f25859c3dc0612231687458885d578f5e3893b4a

**Comment by tdhartwick** [comment]
Fixed somehow :+1:
